# Generated by Django 3.1 on 2021-10-11 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('productID', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('createDate', models.DateTimeField(max_length=50, auto_now=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
